[font]
size = 20.0

[font.bold]
family = "MonaspaceNeon Nerd Font"
style = "Bold"

[font.bold_italic]
family = "MonaspaceNeon Nerd Font"
style = "Bold Italic"

[font.italic]
family = "MonaspaceNeonNerdFont Nerd Font"
style = "Italic"

[font.normal]
family = "MonaspaceNeonNerdFont Nerd Font"
style = "Regular"

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[window]
opacity = 0.98
option_as_alt = "Both"

[window.class]
general = "Alacritty"
instance = "Alacritty"
