#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 2
final_space = true
console_title_template = '{{ .Shell }} in {{ .Folder }}'

[[blocks]]
  type = 'prompt'
  alignment = 'left'

# [[blocks.segments]]
#     type = 'session'
#     style = 'diamond'
#     # foreground = 'p:black'
#     foreground_templates = ['{{ if .SSHSession }}p:black{{ else }}p:yellow{{ end }}']
#     background = 'p:yellow'
#     leading_diamond = ''
#     trailing_diamond = ''
#     template = ' {{ if .SSHSession }} {{ .UserName }}@{{.HostName}}{{ else }} {{ end }} '

[[blocks.segments]]
    type = 'text'
    style = 'diamond'
    leading_diamond = ''
    trailing_diamond = ''
    foreground = 'p:white'
    background = 'p:orange'
    template = ''

[[blocks.segments]]
    type = 'path'
    style = 'powerline'
    powerline_symbol = ''
    foreground = 'p:white'
    background = 'p:orange'
    template = '  {{ path .Path .Location }} '

    [blocks.segments.properties]
      style = 'powerlevel'
      mixed_threshold = 3
      max_depth = 3
      max_width = 30
      hide_root_location = true

[[blocks.segments]]
  type = "project"
  style = "powerline"
  powerline_symbol = ""
  foreground = "#193549"
  background = "#ffeb3b"
  template = " {{ if .Error }}{{ .Error }}{{ else }}{{ if .Version }} {{.Version}}{{ end }} {{ if .Name }}{{ .Name }}{{ end }}{{ end }} "

[[blocks.segments]]
    type = 'git'
    style = 'powerline'
    powerline_symbol = ''
    foreground = 'p:black'
    foreground_templates = ['{{ if or (.Working.Changed) (.Staging.Changed) }}p:black{{ end }}', '{{ if and (gt .Ahead 0) (gt .Behind 0) }}p:white{{ end }}', '{{ if gt .Ahead 0 }}p:white{{ end }}']
    background = 'p:green'
    background_templates = ['{{ if or (.Working.Changed) (.Staging.Changed) }}p:yellow{{ end }}', '{{ if and (gt .Ahead 0) (gt .Behind 0) }}p:red{{ end }}', '{{ if gt .Ahead 0 }}#49416D{{ end }}', '{{ if gt .Behind 0 }}#7A306C{{ end }}']
    template = ' {{ if .UpstreamURL }}{{ url .UpstreamIcon .UpstreamURL }} {{ end }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }} '

    [blocks.segments.properties]
      branch_max_length = 25
      fetch_status = true
      fetch_upstream_icon = true

[[blocks.segments]]
  type = "executiontime"
  style = "powerline"
  powerline_symbol = ""
  foreground = "#ffffff"
  background = "#8800dd"
  template = " <#fefefe></> {{ .FormattedMs }} "

  [properties]
  threshold = 500
  style = "austin"
  always_enabled = true

[[blocks.segments]]
    type = 'status'
    style = 'diamond'
    foreground = 'p:white'
    background = 'p:blue'
    background_templates = ['{{ if gt .Code 0 }}p:red{{ end }}']
    leading_diamond = '<transparent,background></>'
    trailing_diamond = ''
    template = ' {{ if gt .Code 0 }}{{ end }} '

    [blocks.segments.properties]
      always_enabled = true

[[blocks]]
  # type = 'rprompt'
  type = 'prompt'
  alignment = 'right'

[[blocks.segments]]
  type = "text"
  style = "plain"
  foreground = "#E06C75"
  template = ""
#
# [[blocks.segments]]
#     type = 'node'
#     style = 'plain'
#     foreground = 'p:green'
#     background = 'transparent'
#     template = ' '
#
#     [blocks.segments.properties]
#       display_mode = 'files'
#       fetch_package_manager = false
#       home_enabled = false
#
# [[blocks.segments]]
#     type = 'go'
#     style = 'plain'
#     foreground = 'p:orange'
#     background = 'transparent'
#     template = ' {{ .Full }}'
#
#     [blocks.segments.properties]
#       fetch_version = true
#
# [[blocks.segments]]
#     type = 'python'
#     style = 'plain'
#     foreground = 'p:yellow'
#     background = 'transparent'
#     template = ' '
#
#     [blocks.segments.properties]
#       display_mode = 'files'
#       fetch_version = false
#       fetch_virtual_env = false
#

[[tooltips]]
  type = 'aws'
  tips = ['aws']
  style = 'diamond'
  foreground = 'p:white'
  background = 'p:orange'
  leading_diamond = ''
  trailing_diamond = ''
  template = '  {{ .Profile }}{{ if .Region }}@{{ .Region }}{{ end }} '

  [tooltips.properties]
    display_default = true

[[tooltips]]
  type = 'gcp'
  tips = ['gcloud']
  style = 'diamond'
  foreground = 'p:white'
  background = 'p:orange'
  leading_diamond = ''
  trailing_diamond = ''
  template = ' 󰅟 {{ .Project }}{{ if .Region }}@{{ .Region }}{{ end }} '

  [tooltips.properties]
    display_default = true

[[tooltips]]
  type = 'az'
  tips = ['az']
  style = 'diamond'
  foreground = 'p:white'
  background = 'p:blue'
  leading_diamond = ''
  trailing_diamond = ''
  template = '  {{ .Name }} '

  [tooltips.properties]
    display_default = true

[transient_prompt]
  foreground = 'p:black'
  background = 'transparent'
  template = '<p:yellow,transparent></><,p:yellow> {{ .Folder }} </><p:yellow,transparent></> '

[secondary_prompt]
  foreground = 'p:black'
  background = 'transparent'
  template = '<p:yellow,transparent></><,p:yellow> > </><p:yellow,transparent></> '

[palette]
  black = '#262B44'
  blue = '#4B95E9'
  green = '#59C9A5'
  orange = '#F07623'
  red = '#D81E5B'
  white = '#E0DEF4'
  yellow = '#F3AE35'
